{pkgs}: {
  deps = [
    pkgs.pango
    pkgs.gdk-pixbuf
    pkgs.expat
    pkgs.xorg.libXfixes
    pkgs.cairo
    pkgs.alsaLib
    pkgs.xorg.libXScrnSaver
    pkgs.xorg.libXtst
    pkgs.xorg.libXdamage
    pkgs.xorg.libXcursor
    pkgs.xorg.libXcomposite
    pkgs.xorg.libXrandr
    pkgs.xorg.libXrender
    pkgs.xorg.libXi
    pkgs.xorg.libXext
    pkgs.xorg.libX11
    pkgs.alsa-lib
    pkgs.mesa
    pkgs.gtk3
    pkgs.cups
    pkgs.at-spi2-atk
    pkgs.atk
    pkgs.dbus
    pkgs.nspr
    pkgs.nss
    pkgs.firefox
    pkgs.glib
    pkgs.imagemagick
    pkgs.chromium
    pkgs.unzip
    pkgs.jq
    pkgs.ffmpeg
    pkgs.postgresql
    pkgs.lsof
  ];
}
