-- Database Schema Backup - March 25, 2025
-- This file contains the database schema export for the storytelling platform

-- Tables structure exported from information_schema.columns
/*
table_name,column_name,data_type,character_maximum_length
achievements,id,integer,
achievements,name,text,
achievements,description,text,
achievements,type,text,
achievements,condition,json,
achievements,badge_icon,text,
achievements,created_at,timestamp without time zone,
activity_logs,id,integer,
activity_logs,user_id,integer,
activity_logs,action,text,
activity_logs,details,json,
activity_logs,ip_address,text,
activity_logs,user_agent,text,
activity_logs,created_at,timestamp without time zone,
admin_notifications,id,integer,
admin_notifications,title,text,
admin_notifications,message,text,
admin_notifications,type,text,
admin_notifications,is_read,boolean,
admin_notifications,priority,integer,
admin_notifications,created_at,timestamp without time zone,
analytics,id,integer,
analytics,post_id,integer,
analytics,page_views,integer,
analytics,unique_visitors,integer,
analytics,average_read_time,double precision,
analytics,bounce_rate,double precision,
analytics,device_stats,json,
analytics,updated_at,timestamp without time zone,
author_stats,id,integer,
author_stats,author_id,integer,
author_stats,total_posts,integer,
author_stats,total_likes,integer,
author_stats,total_tips,text,
author_stats,updated_at,timestamp without time zone,
author_tips,id,integer,
author_tips,author_id,integer,
author_tips,amount,text,
author_tips,message,text,
author_tips,created_at,timestamp without time zone,
bookmarks,id,integer,
bookmarks,user_id,integer,
bookmarks,post_id,integer,
bookmarks,created_at,timestamp without time zone,
bookmarks,notes,text,
bookmarks,last_position,numeric,
bookmarks,tags,ARRAY,
challenge_entries,id,integer,
challenge_entries,challenge_id,integer,
challenge_entries,user_id,integer,
challenge_entries,content,text,
challenge_entries,submission_date,timestamp without time zone,
comment_reactions,id,integer,
comment_reactions,comment_id,integer,
comment_reactions,user_id,text,
comment_reactions,emoji,text,
comment_reactions,created_at,timestamp without time zone,
comment_votes,id,integer,
comment_votes,comment_id,integer,
comment_votes,user_id,text,
comment_votes,is_upvote,boolean,
comment_votes,created_at,timestamp without time zone,
comments,id,integer,
comments,content,text,
comments,post_id,integer,
comments,parent_id,integer,
comments,user_id,integer,
comments,is_approved,boolean,
comments,edited,boolean,
comments,edited_at,timestamp without time zone,
comments,metadata,json,
comments,created_at,timestamp without time zone,
contact_messages,id,integer,
contact_messages,name,text,
contact_messages,email,text,
contact_messages,subject,text,
contact_messages,message,text,
contact_messages,metadata,json,
contact_messages,created_at,timestamp without time zone,
content_protection,id,integer,
content_protection,content,text,
content_protection,hash,text,
content_protection,created_at,timestamp without time zone,
game_dialogs,id,integer,
game_dialogs,dialog_id,text,
game_dialogs,type,text,
game_dialogs,character_id,text,
game_dialogs,data,json,
game_dialogs,created_at,timestamp without time zone,
game_dialogs,updated_at,timestamp without time zone,
game_items,id,integer,
game_items,item_id,text,
game_items,name,text,
game_items,type,text,
game_items,description,text,
game_items,image_url,text,
game_items,data,json,
game_items,created_at,timestamp without time zone,
game_items,updated_at,timestamp without time zone,
game_progress,id,integer,
game_progress,user_id,integer,
game_progress,current_scene_id,text,
game_progress,visited_scenes,ARRAY,
game_progress,inventory,json,
game_progress,flags,json,
game_progress,game_time,integer,
game_progress,updated_at,timestamp without time zone,
game_puzzles,id,integer,
game_puzzles,puzzle_id,text,
game_puzzles,type,text,
game_puzzles,difficulty,text,
game_puzzles,data,json,
game_puzzles,created_at,timestamp without time zone,
game_puzzles,updated_at,timestamp without time zone,
game_saves,id,integer,
game_saves,save_id,text,
game_saves,user_id,integer,
game_saves,name,text,
game_saves,screenshot,text,
game_saves,game_state,json,
game_saves,playtime,integer,
game_saves,created_at,timestamp without time zone,
game_saves,updated_at,timestamp without time zone,
performance_metrics,id,integer,
performance_metrics,page_id,text,
performance_metrics,load_time,numeric,
performance_metrics,time_to_interactive,numeric,
performance_metrics,first_contentful_paint,numeric,
performance_metrics,largest_contentful_paint,numeric,
performance_metrics,cumulative_layout_shift,numeric,
performance_metrics,created_at,timestamp without time zone,
post_likes,id,integer,
post_likes,post_id,integer,
post_likes,user_id,integer,
post_likes,is_like,boolean,
post_likes,created_at,timestamp without time zone,
posts,id,integer,
posts,title,text,
posts,slug,text,
posts,content,text,
posts,excerpt,text,
posts,author_id,integer,
posts,metadata,json,
posts,created_at,timestamp without time zone,
posts,updated_at,timestamp without time zone,
reading_progress,id,integer,
reading_progress,post_id,integer,
reading_progress,user_id,integer,
reading_progress,progress,double precision,
reading_progress,updated_at,timestamp without time zone,
reported_content,id,integer,
reported_content,content_type,text,
reported_content,content_id,integer,
reported_content,reporter_id,integer,
reported_content,reason,text,
reported_content,status,text,
reported_content,created_at,timestamp without time zone,
reset_tokens,id,integer,
reset_tokens,user_id,integer,
reset_tokens,token,text,
reset_tokens,expires,timestamp without time zone,
reset_tokens,used,boolean,
reset_tokens,created_at,timestamp without time zone,
secret_progress,id,integer,
secret_progress,user_id,integer,
secret_progress,post_id,integer,
secret_progress,discovery_date,timestamp without time zone,
sessions,id,text,
sessions,expires,timestamp without time zone,
sessions,session,json,
sessions,created_at,timestamp without time zone,
site_analytics,id,integer,
site_analytics,date,date,
site_analytics,page_views,integer,
site_analytics,unique_visitors,integer,
site_analytics,average_session_duration,numeric,
site_analytics,bounce_rate,numeric,
site_analytics,top_pages,json,
site_analytics,traffic_sources,json,
site_settings,id,integer,
site_settings,key,text,
site_settings,value,json,
site_settings,category,text,
site_settings,updated_at,timestamp without time zone,
user_achievements,id,integer,
user_achievements,user_id,integer,
user_achievements,achievement_id,integer,
user_achievements,awarded_at,timestamp without time zone,
user_achievements,progress,numeric,
user_feedback,id,integer,
user_feedback,user_id,integer,
user_feedback,title,text,
user_feedback,content,text,
user_feedback,category,text,
user_feedback,status,text,
user_feedback,metadata,json,
user_feedback,created_at,timestamp without time zone,
user_privacy_settings,id,integer,
user_privacy_settings,user_id,integer,
user_privacy_settings,show_reading_history,boolean,
user_privacy_settings,show_comments,boolean,
user_privacy_settings,show_likes,boolean,
user_privacy_settings,show_profile,boolean,
user_privacy_settings,allow_recommendations,boolean,
user_privacy_settings,allow_data_collection,boolean,
user_privacy_settings,updated_at,timestamp without time zone,
user_progress,id,integer,
user_progress,user_id,integer,
user_progress,progress_type,text,
user_progress,current_value,numeric,
user_progress,target_value,numeric,
user_progress,metadata,json,
user_progress,updated_at,timestamp without time zone,
user_streaks,id,integer,
user_streaks,user_id,integer,
user_streaks,streak_type,text,
user_streaks,current_streak,integer,
user_streaks,longest_streak,integer,
user_streaks,last_activity_date,timestamp without time zone,
user_streaks,metadata,json,
user_streaks,updated_at,timestamp without time zone,
users,id,integer,
users,username,text,
users,email,text,
users,password_hash,text,
users,full_name,text,
users,is_admin,boolean,
users,biography,text,
users,avatar,text,
users,metadata,json,
users,created_at,timestamp without time zone,
webhooks,id,integer,
webhooks,url,text,
webhooks,event_type,text,
webhooks,secret,text,
webhooks,is_active,boolean,
webhooks,created_at,timestamp without time zone,
writing_challenges,id,integer,
writing_challenges,title,text,
writing_challenges,description,text,
writing_challenges,prompt,text,
writing_challenges,start_date,timestamp without time zone,
writing_challenges,end_date,timestamp without time zone,
writing_challenges,created_at,timestamp without time zone,
*/

-- The database contains 39 tables with complete relational structure
-- This schema is managed by Drizzle ORM (see shared/schema.ts)
-- Last backup date: March 25, 2025